game.AddParticles("particles/muzzleflashes.pcf")
game.AddParticles("particles/muzzleflashes_test.pcf")
game.AddParticles("particles/muzzleflashes_test_b.pcf")
game.AddParticles("particles/new_muzzleflashes.pcf")
game.AddParticles("particles/new_muzzleflashes_b.pcf")
game.AddParticles("particles/flashbang.pcf")
game.AddParticles("particles/rocket_fx.pcf")
game.AddParticles("particles/fas_explosions.pcf")
game.AddParticles("particles/ammo.pcf")
game.AddParticles("particles/mortar_fx.pcf")

--muzzleflashes
PrecacheParticleSystem("muzzleflash_1") -- SKS, RPK
PrecacheParticleSystem("muzzleflash_3") -- RK95, UMP45, (SG552)
PrecacheParticleSystem("muzzleflash_4") -- G36K, (G36C)
PrecacheParticleSystem("muzzleflash_5") -- (M60E3), ASH12
PrecacheParticleSystem("muzzleflash_6") -- M4A1, M16
PrecacheParticleSystem("muzzleflash_ak47") -- AK47
PrecacheParticleSystem("muzzleflash_ak74") -- AK74
PrecacheParticleSystem("muzzleflash_FAMAS") -- FAMAS F1, SG550
PrecacheParticleSystem("muzzleflash_g3") -- G3A3
PrecacheParticleSystem("muzzleflash_m14") -- M14, L85, (M21)
PrecacheParticleSystem("muzzleflash_M3") -- M3S90, MP153
PrecacheParticleSystem("muzzleflash_m79") -- (M79)
PrecacheParticleSystem("muzzleflash_M82") -- (M82)
PrecacheParticleSystem("muzzleflash_MINIMI") -- (MINIMI)
PrecacheParticleSystem("muzzleflash_mp5") -- MP5A5
PrecacheParticleSystem("muzzleflash_none") -- Undefined --
PrecacheParticleSystem("muzzleflash_none_red") -- Undefined --
PrecacheParticleSystem("muzzleflash_none_smoke") -- Undefined --
PrecacheParticleSystem("muzzleflash_OTS") -- P226, (OTS)
PrecacheParticleSystem("muzzleflash_pistol") -- Glock, M1911, (Beretta F92)
PrecacheParticleSystem("muzzleflash_pistol_cleric") -- Vector
PrecacheParticleSystem("muzzleflash_pistol_deagle") -- Deagle, M40A3
PrecacheParticleSystem("muzzleflash_pistol_red") -- PMM
PrecacheParticleSystem("muzzleflash_shotgun") -- Remington 870, SAIGA12K
PrecacheParticleSystem("muzzleflash_slug") -- KS23
PrecacheParticleSystem("muzzleflash_smg") -- L2A3, UZI, (MK7A4), (MAC11)
PrecacheParticleSystem("muzzleflash_smg_bizon") -- Bizon
PrecacheParticleSystem("muzzleflash_suppressed") -- All Rifles
PrecacheParticleSystem("party_spark") -- Undefined --
PrecacheParticleSystem("port_smoke_heavy") -- Undefined --
PrecacheParticleSystem("muzzle_rockets") -- RPG26
PrecacheParticleSystem("muzzleflash_1bb") -- Undefined --
PrecacheParticleSystem("muzzleflash_3bb") -- AK104
PrecacheParticleSystem("muzzleflash_4bb") -- FN P90
PrecacheParticleSystem("muzzleflash_6b") -- FN FAL
PrecacheParticleSystem("muzzleflash_m24") -- M24
PrecacheParticleSystem("muzzleflash_pistol_rbull") -- Raging bull
PrecacheParticleSystem("muzzleflash_SR25") -- SR25, M110
PrecacheParticleSystem("muzzleflash_svd") -- SVD, Kar98K
PrecacheParticleSystem("muzzleflash_vollmer") -- MC51B Vollmer

PrecacheParticleSystem("explosion_claymore") -- medium
PrecacheParticleSystem("explosion_HE_claymore") -- big
PrecacheParticleSystem("explosion_grenade") -- medium
PrecacheParticleSystem("explosion_he_grenade") -- big
PrecacheParticleSystem("explosion_m79") -- medium
PrecacheParticleSystem("explosion_HE_m79") -- big
PrecacheParticleSystem("explosion_m79_body") -- playerhit
PrecacheParticleSystem("party_fireworks") --
PrecacheParticleSystem("explosion_water") --


PrecacheParticleSystem("burning_character") -- playerburning
PrecacheParticleSystem("fire_vehicle") -- helicrush
PrecacheParticleSystem("fire_jet_01") -- heliflyburn
PrecacheParticleSystem("embers_large_01") -- map
PrecacheParticleSystem("embers_large_02") -- map

PrecacheParticleSystem("explosion_flashbang") -- medium
PrecacheParticleSystem("explosion_he_flashbang") -- big
PrecacheParticleSystem("HE_smoke_grenade_smoke") -- m18 purple
PrecacheParticleSystem("smoke_grenade_smoke") -- m18 green
PrecacheParticleSystem("artillery_smoke_blue") -- flare
PrecacheParticleSystem("artillery_smoke_red") -- flare
PrecacheParticleSystem("m79_trail") -- 

PrecacheParticleSystem("muzzle_glow_pistol_blue")
PrecacheParticleSystem("new_muzzle_center_b")
PrecacheParticleSystem("new_muzzle_center_ak")
PrecacheParticleSystem("m82_shocksmoke_trace")
PrecacheParticleSystem("muzzle_smoke_shot_b")
PrecacheParticleSystem("new_muzzle_center_bizon")
PrecacheParticleSystem("muzzleflash_m14")
PrecacheParticleSystem("muzzleflash_5_lmg_break_e")
PrecacheParticleSystem("muzzle_center_heavy_lmg")
PrecacheParticleSystem("muzzleflash_5")
PrecacheParticleSystem("muzzleflash_5_lmg_break_a")
PrecacheParticleSystem("muzzleflash_5_lmg_break_b")
PrecacheParticleSystem("muzzleflash_5_lmg_break_c")
PrecacheParticleSystem("muzzleflash_5_lmg_break_d")
PrecacheParticleSystem("muzzleflash_6")
PrecacheParticleSystem("muzzleflash_6_break_a")
PrecacheParticleSystem("muzzleflash_6_break_b")
PrecacheParticleSystem("muzzleflash_6_break_c")
PrecacheParticleSystem("muzzleflash_6_break_d")
PrecacheParticleSystem("muzzleflash_6_break_e")
PrecacheParticleSystem("muzzleflash_6_break_f")
PrecacheParticleSystem("muzzle_heatwave")
PrecacheParticleSystem("muzzle_center_big")
PrecacheParticleSystem("muzzle_glow")

PrecacheParticleSystem("muzzleflash_m79")
PrecacheParticleSystem("muzzle_sparks_big")
PrecacheParticleSystem("muzzleflash_pistol_deagle")
PrecacheParticleSystem("muzzleflash_slug_flame")
PrecacheParticleSystem("muzzle_center_medium")
PrecacheParticleSystem("muzzleflash_slug")
PrecacheParticleSystem("muzzle_sparks_thin")
PrecacheParticleSystem("muzzle_trace_blue")
PrecacheParticleSystem("muzzle_bullet_trail_shotgun")
PrecacheParticleSystem("muzzleflash_mp5")
PrecacheParticleSystem("muzzleflash_g3")
PrecacheParticleSystem("muzzleflash_6_break_a1")
PrecacheParticleSystem("muzzleflash_6_break_b1")
PrecacheParticleSystem("muzzleflash_6_break_c1")
PrecacheParticleSystem("muzzleflash_6_break_d1")
PrecacheParticleSystem("muzzleflash_6_break_e1")
PrecacheParticleSystem("muzzleflash_6_break_f1")
PrecacheParticleSystem("muzzle_heavy_flame")
PrecacheParticleSystem("muzzle_center_pistol_blue")
PrecacheParticleSystem("muzzle_sparks_ar")
PrecacheParticleSystem("muzzleflash_none_red")
PrecacheParticleSystem("muzzle_center_smg")
PrecacheParticleSystem("muzzle_glow_small_b")
PrecacheParticleSystem("muzzle_center_smg_b")

PrecacheParticleSystem("muzzle_trace")
PrecacheParticleSystem("muzzleflash_pistol")
PrecacheParticleSystem("new_muzzle_center_blue")
PrecacheParticleSystem("muzzle_center_M82")
PrecacheParticleSystem("muzzleflash_pistol_red")
PrecacheParticleSystem("muzzle_center_pistol")
PrecacheParticleSystem("muzzleflash_M3")
PrecacheParticleSystem("m82_shocksmoke")
PrecacheParticleSystem("muzzle_glow_pistol")
PrecacheParticleSystem("muzzleflash_suppressed")
PrecacheParticleSystem("muzzle_supressed_smoke_b")
PrecacheParticleSystem("muzzle_glow_M82")
PrecacheParticleSystem("muzzle_supressed_smoke_d")
PrecacheParticleSystem("muzzle_supressed_trace")
PrecacheParticleSystem("muzzle_sparks_supressed")
PrecacheParticleSystem("muzzleflash_4")
PrecacheParticleSystem("muzzleflash_4_break_a")
PrecacheParticleSystem("muzzleflash_4_break_b")
PrecacheParticleSystem("muzzleflash_4_break_c")
PrecacheParticleSystem("muzzleflash_4_break_d")
PrecacheParticleSystem("muzzleflash_ak74")
PrecacheParticleSystem("muzzleflash_ak74_break_a")
PrecacheParticleSystem("muzzleflash_ak74_break_b")
PrecacheParticleSystem("muzzleflash_ak47")

PrecacheParticleSystem("muzzle_center_ak")
PrecacheParticleSystem("shellsmoke")
PrecacheParticleSystem("new_muzzle_center_blue_b")
PrecacheParticleSystem("muzzle_glow_blue")
PrecacheParticleSystem("test_mp5")
PrecacheParticleSystem("muzzle_glow_ak")
PrecacheParticleSystem("muzzleflash_3")
PrecacheParticleSystem("muzzleflash_3_break_a")
PrecacheParticleSystem("muzzleflash_3_break_b")
PrecacheParticleSystem("muzzleflash_3_break_c")
PrecacheParticleSystem("muzzle_center_lmg_d")
PrecacheParticleSystem("muzzleflash_1")
PrecacheParticleSystem("muzzle_lmg_heavy_flame")
PrecacheParticleSystem("muzzle_glow_lmg")
PrecacheParticleSystem("muzzleflash_M82")
PrecacheParticleSystem("muzzle_m82_flame")
PrecacheParticleSystem("muzzle_m82_flame_b")
PrecacheParticleSystem("muzzle_m82_flame_c")
PrecacheParticleSystem("muzzleflash_MINIMI")
PrecacheParticleSystem("muzzleflash_lmg_break")
PrecacheParticleSystem("muzzle_glow_b")
PrecacheParticleSystem("barrel_smoke_trail")
PrecacheParticleSystem("barrel_smoke")
PrecacheParticleSystem("muzzle_glow_big")

PrecacheParticleSystem("muzzle_center_ak")
PrecacheParticleSystem("shellsmoke")
PrecacheParticleSystem("new_muzzle_center_blue_b")
PrecacheParticleSystem("muzzle_glow_blue")
PrecacheParticleSystem("test_mp5")
PrecacheParticleSystem("muzzle_glow_ak")
PrecacheParticleSystem("muzzleflash_3")
PrecacheParticleSystem("muzzleflash_3_break_a")
PrecacheParticleSystem("muzzleflash_3_break_b")
PrecacheParticleSystem("muzzleflash_3_break_c")
PrecacheParticleSystem("muzzle_center_lmg_d")
PrecacheParticleSystem("muzzleflash_1")
PrecacheParticleSystem("muzzle_lmg_heavy_flame")
PrecacheParticleSystem("muzzle_glow_lmg")
PrecacheParticleSystem("muzzleflash_M82")
PrecacheParticleSystem("muzzle_m82_flame")
PrecacheParticleSystem("muzzle_m82_flame_b")
PrecacheParticleSystem("muzzle_m82_flame_c")
PrecacheParticleSystem("muzzleflash_MINIMI")
PrecacheParticleSystem("muzzleflash_lmg_break")
PrecacheParticleSystem("muzzle_glow_b")
PrecacheParticleSystem("barrel_smoke_trail")
PrecacheParticleSystem("barrel_smoke")
PrecacheParticleSystem("muzzle_glow_big")

PrecacheParticleSystem("port_smoke_heavy")
PrecacheParticleSystem("port_shellsmoke")
PrecacheParticleSystem("port_shellsmoke_b")
PrecacheParticleSystem("port_sparks")
PrecacheParticleSystem("port_flames")
PrecacheParticleSystem("port_smoke")
PrecacheParticleSystem("port_glow")
PrecacheParticleSystem("barrel_smoke_plume")
PrecacheParticleSystem("muzzle_smoke_b")
PrecacheParticleSystem("muzzle_center_heavy")
PrecacheParticleSystem("muzzle_sparks_lmg")
PrecacheParticleSystem("muzzle_smoke_c")
PrecacheParticleSystem("muzzleflash_m14_break_a")
PrecacheParticleSystem("muzzleflash_m14_break_b")
PrecacheParticleSystem("muzzleflash_m14_break_c")
PrecacheParticleSystem("muzzleflash_m14_break_d")
PrecacheParticleSystem("muzzleflash_m14_break_e")
PrecacheParticleSystem("muzzleflash_smg_bizon")
PrecacheParticleSystem("muzzle_center_bizon")
PrecacheParticleSystem("muzzleflash_bizon_break_a")
PrecacheParticleSystem("muzzleflash_bizon_break_b")
PrecacheParticleSystem("new_muzzle_center")
PrecacheParticleSystem("muzzle_center_pistol_cleric")
PrecacheParticleSystem("muzzleflash_pistol_cleric")

PrecacheParticleSystem("muzzleflash_pistol_cleric_break_a")
PrecacheParticleSystem("muzzleflash_pistol_cleric_break_b")
PrecacheParticleSystem("muzzleflash_pistol_cleric_break_c")
PrecacheParticleSystem("muzzleflash_pistol_cleric_break_d")
PrecacheParticleSystem("muzzleflash_pistol_cleric_flame_a")
PrecacheParticleSystem("muzzleflash_pistol_cleric_flame_b")
PrecacheParticleSystem("muzzleflash_pistol_cleric_flame_c")
PrecacheParticleSystem("muzzleflash_pistol_cleric_flame_d")
PrecacheParticleSystem("muzzleflash_6_break_a2")
PrecacheParticleSystem("muzzleflash_6_break_b2")
PrecacheParticleSystem("muzzleflash_6_break_c2")
PrecacheParticleSystem("muzzleflash_6_break_d2")
PrecacheParticleSystem("muzzleflash_6_break_e2")
PrecacheParticleSystem("muzzleflash_6_break_f2")
PrecacheParticleSystem("muzzleflash_none_smoke")
PrecacheParticleSystem("muzzleflash_OTS")
PrecacheParticleSystem("muzzle_center_pistol_OTS")
PrecacheParticleSystem("muzzle_sparks_spray")
PrecacheParticleSystem("muzzleflash_shotgun")
PrecacheParticleSystem("muzzle_center_flamering")
PrecacheParticleSystem("barrel_smoke_trail_b")
PrecacheParticleSystem("muzzleflash_none")
PrecacheParticleSystem("muzzle_smoke_d")
PrecacheParticleSystem("test")

PrecacheParticleSystem("testb")
PrecacheParticleSystem("testc")
PrecacheParticleSystem("testd")
PrecacheParticleSystem("test_bizon")
PrecacheParticleSystem("muzzleflash_smg")
PrecacheParticleSystem("muzzleflash_FAMAS")
PrecacheParticleSystem("muzzle_glow_distant")
PrecacheParticleSystem("party_spark")
PrecacheParticleSystem("party_sparkles")
PrecacheParticleSystem("party_glow")
PrecacheParticleSystem("testd_red")
PrecacheParticleSystem("muzzle_flame")

PrecacheParticleSystem("muzzle_glow_pistol_blueb")
PrecacheParticleSystem("muzzleflash_m14_break_eb")
PrecacheParticleSystem("muzzleflash_m14_break_db")
PrecacheParticleSystem("muzzleflash_m14_break_cb")
PrecacheParticleSystem("muzzleflash_m14_break_bb")
PrecacheParticleSystem("muzzleflash_6_lmg_break_eb")
PrecacheParticleSystem("muzzleflash_6_lmg_break_fb")
PrecacheParticleSystem("muzzleflash_5_lmg_break_eb")
PrecacheParticleSystem("barrel_smoke_trailb")
PrecacheParticleSystem("muzzleflash_m14_break_ab")
PrecacheParticleSystem("muzzleflash_5_lmg_break_ab")
PrecacheParticleSystem("muzzleflash_5_lmg_break_bb")

PrecacheParticleSystem("muzzleflash_5_lmg_break_cb")
PrecacheParticleSystem("muzzleflash_5_lmg_break_db")
PrecacheParticleSystem("muzzleflash_6b")
PrecacheParticleSystem("muzzleflash_6_break_ab")
PrecacheParticleSystem("muzzleflash_6_break_bb")
PrecacheParticleSystem("muzzleflash_6_break_cb")
PrecacheParticleSystem("muzzleflash_6_break_db")
PrecacheParticleSystem("muzzleflash_6_break_eb")
PrecacheParticleSystem("muzzleflash_6_break_fb")
PrecacheParticleSystem("muzzle_heatwaveb")
PrecacheParticleSystem("muzzle_center_rbull")
PrecacheParticleSystem("muzzle_glowb")
PrecacheParticleSystem("barrel_smokeb")
PrecacheParticleSystem("muzzle_sparks_bigb")
PrecacheParticleSystem("muzzle_center_M82b")
PrecacheParticleSystem("muzzleflash_slug_flameb")
PrecacheParticleSystem("muzzle_center_mediumb")
PrecacheParticleSystem("muzzle_center_heavy_lmgb")
PrecacheParticleSystem("muzzle_sparks_thinb")
PrecacheParticleSystem("muzzle_bullet_trailb")
PrecacheParticleSystem("muzzle_bullet_trail_shotgunb")
PrecacheParticleSystem("muzzle_bullet_trail_ARb")
PrecacheParticleSystem("muzzle_glow_smallb")
PrecacheParticleSystem("new_muzzle_center_b")

PrecacheParticleSystem("muzzleflash_6_break_a1b")
PrecacheParticleSystem("muzzleflash_6_break_b1b")
PrecacheParticleSystem("muzzleflash_6_break_c1b")
PrecacheParticleSystem("muzzleflash_6_break_d1b")
PrecacheParticleSystem("muzzleflash_6_break_e1b")
PrecacheParticleSystem("muzzleflash_6_break_f1b")
PrecacheParticleSystem("muzzle_heavy_flameb")
PrecacheParticleSystem("muzzle_center_pistol_blueb")
PrecacheParticleSystem("muzzle_sparks_arb")
PrecacheParticleSystem("muzzle_smoke_shotb")
PrecacheParticleSystem("muzzle_smoke_bb")
PrecacheParticleSystem("muzzle_glow_small_bb")
PrecacheParticleSystem("barrel_smoke_plumeb")
PrecacheParticleSystem("muzzle_traceb")
PrecacheParticleSystem("muzzleflash_svd")
PrecacheParticleSystem("new_muzzle_center_blueb")
PrecacheParticleSystem("muzzle_smokeb")
PrecacheParticleSystem("muzzle_glow_M82b")
PrecacheParticleSystem("muzzle_center_pistolb")
PrecacheParticleSystem("muzzle_sparks_lmgb")
PrecacheParticleSystem("muzzle_smoke_cb")
PrecacheParticleSystem("muzzle_glow_pistolb")
PrecacheParticleSystem("muzzle_smoke_shot_bb")
PrecacheParticleSystem("muzzle_supressed_smoke_bb")
PrecacheParticleSystem("muzzle_supressed_smoke_cb")
PrecacheParticleSystem("muzzle_supressed_smoke_db")
PrecacheParticleSystem("muzzle_supressed_traceb")
PrecacheParticleSystem("muzzle_sparks_supressedb")
PrecacheParticleSystem("muzzleflash_4bb")
PrecacheParticleSystem("muzzleflash_4_break_ab")
PrecacheParticleSystem("muzzleflash_4_break_bb")
PrecacheParticleSystem("muzzleflash_4_break_cb")
PrecacheParticleSystem("muzzleflash_4_break_db")
PrecacheParticleSystem("muzzleflash_bizon_break_bb")
PrecacheParticleSystem("muzzleflash_bizon_break_ab")
PrecacheParticleSystem("muzzle_center_bizonb")
PrecacheParticleSystem("new_muzzle_centerbb")
PrecacheParticleSystem("muzzle_center_akb")
PrecacheParticleSystem("muzzle_glow_bigb")
PrecacheParticleSystem("new_muzzle_center_blue_bb")
PrecacheParticleSystem("muzzle_glow_blueb")
PrecacheParticleSystem("muzzle_trace_blueb")
PrecacheParticleSystem("muzzle_center_heavyb")
PrecacheParticleSystem("muzzleflash_3bb")
PrecacheParticleSystem("muzzleflash_3_break_ab")
PrecacheParticleSystem("muzzleflash_3_break_bb")
PrecacheParticleSystem("muzzleflash_3_break_cb")
PrecacheParticleSystem("new_muzzle_center_b")

PrecacheParticleSystem("muzzleflash_1bb")
PrecacheParticleSystem("muzzle_lmg_heavy_flameb")
PrecacheParticleSystem("muzzle_glow_lmgb")
PrecacheParticleSystem("m82_shocksmoke_traceb")
PrecacheParticleSystem("muzzle_m82_flameb")
PrecacheParticleSystem("muzzle_m82_flame_bb")
PrecacheParticleSystem("muzzle_m82_flame_cb")
PrecacheParticleSystem("m82_shocksmokeb")
PrecacheParticleSystem("muzzleflash_lmg_breakb")
PrecacheParticleSystem("muzzle_glow_bb")
PrecacheParticleSystem("muzzleflash_SR25")
PrecacheParticleSystem("muzzleflash_sr25_break_a")
PrecacheParticleSystem("muzzleflash_sr25_break_b")
PrecacheParticleSystem("muzzleflash_sr25_break_c")
PrecacheParticleSystem("muzzleflash_sr25_break_e")
PrecacheParticleSystem("muzzleflash_sr25_break_d")
PrecacheParticleSystem("muzzleflash_pistol_rbull")
PrecacheParticleSystem("muzzle_center_smg_blue")
PrecacheParticleSystem("muzzleflash_m24")
PrecacheParticleSystem("muzzle_glow_white")
PrecacheParticleSystem("muzzleflash_vollmer")
PrecacheParticleSystem("muzzle_sparks_revolver")
PrecacheParticleSystem("muzzle_sparks_spit")
PrecacheParticleSystem("muzzle_center_smg")
PrecacheParticleSystem("muzzle_center_m24")

PrecacheParticleSystem("muzzle_glow_pistol_blue")
PrecacheParticleSystem("new_muzzle_center_b")
PrecacheParticleSystem("new_muzzle_center_ak")
PrecacheParticleSystem("m82_shocksmoke_trace")
PrecacheParticleSystem("muzzle_smoke_shot_b")
PrecacheParticleSystem("new_muzzle_center_bizon")
PrecacheParticleSystem("muzzleflash_m14")
PrecacheParticleSystem("muzzleflash_5_lmg_break_e")
PrecacheParticleSystem("muzzle_center_heavy_lmg")
PrecacheParticleSystem("muzzleflash_5")
PrecacheParticleSystem("muzzleflash_5_lmg_break_a")
PrecacheParticleSystem("muzzleflash_5_lmg_break_b")
PrecacheParticleSystem("muzzleflash_5_lmg_break_c")
PrecacheParticleSystem("muzzleflash_5_lmg_break_d")
PrecacheParticleSystem("muzzleflash_6")
PrecacheParticleSystem("muzzleflash_6_break_a")
PrecacheParticleSystem("muzzleflash_6_break_b")
PrecacheParticleSystem("muzzleflash_6_break_c")
PrecacheParticleSystem("muzzleflash_6_break_d")
PrecacheParticleSystem("muzzleflash_6_break_e")
PrecacheParticleSystem("muzzleflash_6_break_f")
PrecacheParticleSystem("muzzle_heatwave")
PrecacheParticleSystem("muzzle_center_big")
PrecacheParticleSystem("muzzle_glow")
PrecacheParticleSystem("muzzleflash_m79")
PrecacheParticleSystem("muzzle_sparks_big")
PrecacheParticleSystem("muzzleflash_pistol_deagle")
PrecacheParticleSystem("muzzleflash_slug_flame")
PrecacheParticleSystem("muzzle_center_medium")
PrecacheParticleSystem("muzzleflash_slug")
PrecacheParticleSystem("muzzle_sparks_thin")
PrecacheParticleSystem("muzzle_bullet_trail")
PrecacheParticleSystem("muzzle_bullet_trail_shotgun")
PrecacheParticleSystem("muzzle_bullet_trail_AR")
PrecacheParticleSystem("muzzle_glow_small")
PrecacheParticleSystem("muzzleflash_g3")
PrecacheParticleSystem("muzzleflash_6_break_a1")
PrecacheParticleSystem("muzzleflash_6_break_b1")
PrecacheParticleSystem("muzzleflash_6_break_c1")
PrecacheParticleSystem("muzzleflash_6_break_d1")
PrecacheParticleSystem("muzzleflash_6_break_e1")
PrecacheParticleSystem("muzzleflash_6_break_f1")
PrecacheParticleSystem("muzzle_heavy_flame")
PrecacheParticleSystem("muzzle_center_pistol_blue")
PrecacheParticleSystem("muzzle_sparks_ar")
PrecacheParticleSystem("muzzleflash_smg")
PrecacheParticleSystem("muzzle_center_smg")
PrecacheParticleSystem("muzzle_glow_small_b")
PrecacheParticleSystem("muzzle_center_smg_b")
PrecacheParticleSystem("muzzle_trace")
PrecacheParticleSystem("muzzleflash_pistol")
PrecacheParticleSystem("new_muzzle_center_blue")
PrecacheParticleSystem("muzzle_center_M82")
PrecacheParticleSystem("muzzleflash_pistol_red")
PrecacheParticleSystem("muzzle_center_pistol")
PrecacheParticleSystem("muzzleflash_M3")
PrecacheParticleSystem("m82_shocksmoke")
PrecacheParticleSystem("muzzle_glow_pistol")
PrecacheParticleSystem("muzzleflash_suppressed")
PrecacheParticleSystem("muzzle_supressed_smoke_b")
PrecacheParticleSystem("muzzle_glow_M82")
PrecacheParticleSystem("muzzle_supressed_smoke_d")
PrecacheParticleSystem("muzzle_supressed_trace")
PrecacheParticleSystem("muzzle_sparks_supressed")
PrecacheParticleSystem("muzzleflash_4")
PrecacheParticleSystem("muzzleflash_4_break_a")
PrecacheParticleSystem("muzzleflash_4_break_b")
PrecacheParticleSystem("muzzleflash_4_break_c")
PrecacheParticleSystem("muzzleflash_4_break_d")
PrecacheParticleSystem("muzzleflash_ak74")
PrecacheParticleSystem("muzzleflash_ak74_break_a")

PrecacheParticleSystem("muzzleflash_ak74_break_b")
PrecacheParticleSystem("muzzleflash_ak47")
PrecacheParticleSystem("muzzle_center_ak")
PrecacheParticleSystem("shellsmoke")
PrecacheParticleSystem("new_muzzle_center_blue_b")
PrecacheParticleSystem("muzzle_glow_blue")
PrecacheParticleSystem("muzzle_trace_blue")
PrecacheParticleSystem("muzzle_glow_ak")
PrecacheParticleSystem("muzzleflash_3")
PrecacheParticleSystem("muzzleflash_3_break_a")
PrecacheParticleSystem("muzzleflash_3_break_b")
PrecacheParticleSystem("muzzleflash_3_break_c")
PrecacheParticleSystem("muzzle_center_lmg_d")
PrecacheParticleSystem("muzzleflash_1")
PrecacheParticleSystem("muzzle_lmg_heavy_flame")
PrecacheParticleSystem("muzzle_glow_lmg")
PrecacheParticleSystem("muzzleflash_M82")
PrecacheParticleSystem("muzzle_m82_flame")
PrecacheParticleSystem("muzzle_m82_flame_b")
PrecacheParticleSystem("muzzle_m82_flame_c")
PrecacheParticleSystem("muzzleflash_MINIMI")
PrecacheParticleSystem("muzzleflash_lmg_break")
PrecacheParticleSystem("muzzle_glow_b")
PrecacheParticleSystem("barrel_smoke_trail")
PrecacheParticleSystem("barrel_smoke")
PrecacheParticleSystem("muzzle_glow_big")
PrecacheParticleSystem("port_smoke_heavy")
PrecacheParticleSystem("port_shellsmoke")
PrecacheParticleSystem("port_shellsmoke_b")
PrecacheParticleSystem("port_sparks")
PrecacheParticleSystem("port_flames")
PrecacheParticleSystem("port_smoke")
PrecacheParticleSystem("port_glow")
PrecacheParticleSystem("barrel_smoke_plume")
PrecacheParticleSystem("muzzle_smoke_b")
PrecacheParticleSystem("muzzle_center_heavy")
PrecacheParticleSystem("muzzle_sparks_lmg")
PrecacheParticleSystem("muzzle_smoke_c")
PrecacheParticleSystem("muzzleflash_m14_break_a")
PrecacheParticleSystem("muzzleflash_m14_break_b")
PrecacheParticleSystem("muzzleflash_m14_break_c")
PrecacheParticleSystem("muzzleflash_m14_break_d")
PrecacheParticleSystem("muzzleflash_m14_break_e")
PrecacheParticleSystem("muzzleflash_smg_bizon")
PrecacheParticleSystem("muzzle_center_bizon")
PrecacheParticleSystem("muzzleflash_bizon_break_a")
PrecacheParticleSystem("muzzleflash_bizon_break_b")
PrecacheParticleSystem("new_muzzle_center")
PrecacheParticleSystem("muzzle_center_pistol_cleric")
PrecacheParticleSystem("muzzleflash_pistol_cleric")
PrecacheParticleSystem("muzzleflash_pistol_cleric_break_a")
PrecacheParticleSystem("muzzleflash_pistol_cleric_break_b")
PrecacheParticleSystem("muzzleflash_pistol_cleric_break_c")
PrecacheParticleSystem("muzzleflash_pistol_cleric_break_d")
PrecacheParticleSystem("muzzleflash_pistol_cleric_flame_a")
PrecacheParticleSystem("muzzleflash_pistol_cleric_flame_b")
PrecacheParticleSystem("muzzleflash_pistol_cleric_flame_c")
PrecacheParticleSystem("muzzleflash_pistol_cleric_flame_d")
PrecacheParticleSystem("muzzleflash_6_break_a2")
PrecacheParticleSystem("muzzleflash_6_break_b2")
PrecacheParticleSystem("muzzleflash_6_break_c2")
PrecacheParticleSystem("muzzleflash_6_break_d2")
PrecacheParticleSystem("muzzleflash_6_break_e2")
PrecacheParticleSystem("muzzleflash_6_break_f2")
PrecacheParticleSystem("muzzleflash_FAMAS")
PrecacheParticleSystem("muzzleflash_OTS")
PrecacheParticleSystem("muzzle_center_pistol_OTS")
PrecacheParticleSystem("muzzle_sparks_spray")
PrecacheParticleSystem("muzzleflash_shotgun")
PrecacheParticleSystem("muzzle_center_flamering")
PrecacheParticleSystem("barrel_smoke_trail_b")
PrecacheParticleSystem("muzzleflash_none")
PrecacheParticleSystem("muzzle_smoke_d")
PrecacheParticleSystem("test")
PrecacheParticleSystem("testb")
PrecacheParticleSystem("testc")
PrecacheParticleSystem("testd")

PrecacheParticleSystem("ammo_box_explosion")
PrecacheParticleSystem("ammo_box_explosion_smoke")
PrecacheParticleSystem("ammo_box_flash")
PrecacheParticleSystem("ammo_box_flash_b")
PrecacheParticleSystem("ammo_box_flashes")
PrecacheParticleSystem("ammo_box_flashes_b")
PrecacheParticleSystem("ammo_box_sparks")
PrecacheParticleSystem("ammo_box_explosion_flames")
PrecacheParticleSystem("ammo_box_flames_glow")
PrecacheParticleSystem("ammo_box_flames")
PrecacheParticleSystem("ammo_box_flames_glow_b")
PrecacheParticleSystem("ammo_box_sparks_b")
PrecacheParticleSystem("ammo_box_trails")
PrecacheParticleSystem("ammo_box_debris")
PrecacheParticleSystem("ammo_box_debris_smoke")
PrecacheParticleSystem("ammo_box_debris_sparks")
PrecacheParticleSystem("ammo_box_flames")
PrecacheParticleSystem("ammo_box_flames_glow_b")
PrecacheParticleSystem("ammo_box_sparks_b")
PrecacheParticleSystem("ammo_box_trails")

PrecacheParticleSystem("explosion_grenadeb")
PrecacheParticleSystem("gr_1")
PrecacheParticleSystem("gr_2")
PrecacheParticleSystem("gr_3child")
PrecacheParticleSystem("gr_3ref")
PrecacheParticleSystem("gr_4")
PrecacheParticleSystem("gr_5")
PrecacheParticleSystem("gr_6warp")
PrecacheParticleSystem("gr_7rests")
PrecacheParticleSystem("mt_7rests")
PrecacheParticleSystem("mt_1")
PrecacheParticleSystem("mt_2")
PrecacheParticleSystem("mt_3child")
PrecacheParticleSystem("mt_3ref")
PrecacheParticleSystem("mt_4")
PrecacheParticleSystem("mt_5")
PrecacheParticleSystem("mt_6warp")
PrecacheParticleSystem("explosion_mortarb")
PrecacheParticleSystem("mt_4below")
PrecacheParticleSystem("mt_8bits")

PrecacheParticleSystem("airstrike_smoke")
PrecacheParticleSystem("airstrike_flash")
PrecacheParticleSystem("airstrike_bigspike")
PrecacheParticleSystem("airstrike_bigspike_b")
PrecacheParticleSystem("airstrike_bigspike_c")
PrecacheParticleSystem("airstrike_offspikes")
PrecacheParticleSystem("airstrike_offspikes_b")
PrecacheParticleSystem("airstrike_offspikes_group")
PrecacheParticleSystem("airstrike_offspikes_c")
PrecacheParticleSystem("airstrike_spikes")
PrecacheParticleSystem("airstrike_offspikes_d")
PrecacheParticleSystem("airstrike_bigspike_d")
PrecacheParticleSystem("airstrike_smoke_b")
PrecacheParticleSystem("airstrike_smoke_c")
PrecacheParticleSystem("airstrike_flash_b")
PrecacheParticleSystem("airstrike_flames")
PrecacheParticleSystem("airstrike_flames_glow")
PrecacheParticleSystem("airstrike_flames_b")
PrecacheParticleSystem("airstrike_sparks")
PrecacheParticleSystem("airstrike_sparks_b")

PrecacheParticleSystem("airstrike_sparks_c")
PrecacheParticleSystem("airstrike_smoke_d")
PrecacheParticleSystem("airstrike_smoke_e")
PrecacheParticleSystem("airstrike_spikes_b")
PrecacheParticleSystem("airstrike_offspikes_fast")
PrecacheParticleSystem("airstrike_offspikes_fast_b")
PrecacheParticleSystem("airstrike_offspikes_fast_group")
PrecacheParticleSystem("airstrike_debris")
PrecacheParticleSystem("airstrike_flash_c")
PrecacheParticleSystem("airstrike_flash_d")
PrecacheParticleSystem("airstrike_shockwave")
PrecacheParticleSystem("airstrike_shockwave_b")
PrecacheParticleSystem("airstrike_shrapnel")
PrecacheParticleSystem("airstrike_shrapnel_b")
PrecacheParticleSystem("airstrike_shrapnel_c")
PrecacheParticleSystem("airstrike_shrapnel_group")
PrecacheParticleSystem("airstrike_debris_b")

PrecacheParticleSystem("flashbang_sparks")
PrecacheParticleSystem("flashbang_sparks_b")
PrecacheParticleSystem("flashbang_flash")
PrecacheParticleSystem("flashbang_flash_b")
PrecacheParticleSystem("flashbang_sparks_c")
PrecacheParticleSystem("flashbang_smoke")
PrecacheParticleSystem("flashbang_smoke_b")
PrecacheParticleSystem("HE_flashbang_bang_a")
PrecacheParticleSystem("HE_flashbang_flash")
PrecacheParticleSystem("HE_flashbang_bang_b")
PrecacheParticleSystem("explosion_he_flashbang")
PrecacheParticleSystem("HE_flashbang_sparks")
PrecacheParticleSystem("HE_flashbang_rays")
PrecacheParticleSystem("HE_flashbang_smoke")

PrecacheParticleSystem("explosion")
PrecacheParticleSystem("explosion_b")
PrecacheParticleSystem("explosion_c")
PrecacheParticleSystem("airstrike_bigspike")
PrecacheParticleSystem("explosion_e")
PrecacheParticleSystem("smoke_trails")
PrecacheParticleSystem("debris")
PrecacheParticleSystem("debris_trail")
PrecacheParticleSystem("debris_trail_b")
PrecacheParticleSystem("debris_trail_group")
PrecacheParticleSystem("debris_trail_c")
PrecacheParticleSystem("debris_trail_d")
PrecacheParticleSystem("flames")
PrecacheParticleSystem("flamesb")

PrecacheParticleSystem("flash")
PrecacheParticleSystem("dust")
PrecacheParticleSystem("flash_c")
PrecacheParticleSystem("debris_glow")
PrecacheParticleSystem("debris_glow_b")
PrecacheParticleSystem("smoke_trails_b")
PrecacheParticleSystem("flash_b")
PrecacheParticleSystem("shockwave_trace")
PrecacheParticleSystem("shockwave_dust")
PrecacheParticleSystem("debris_embers")
PrecacheParticleSystem("flash_ground")
PrecacheParticleSystem("shockwave")
PrecacheParticleSystem("debris_chunks")
PrecacheParticleSystem("debris_ash")
PrecacheParticleSystem("cloudwave")
PrecacheParticleSystem("dustcloud")
PrecacheParticleSystem("shockwave_dust_b")
PrecacheParticleSystem("fireflies")


PrecacheParticleSystem("snow_01")
PrecacheParticleSystem("snow_02_fog")
PrecacheParticleSystem("reference_1")
PrecacheParticleSystem("snow_01_fast")
PrecacheParticleSystem("snow_02_fog_fast")
PrecacheParticleSystem("reference_2")
PrecacheParticleSystem("static_fog_01")
PrecacheParticleSystem("static_fog_02")
PrecacheParticleSystem("snow_01_support")
PrecacheParticleSystem("snow_03_cheapfog")
PrecacheParticleSystem("reference_1_cheap")
PrecacheParticleSystem("snow_04")
PrecacheParticleSystem("snow_04_fast")
PrecacheParticleSystem("snow_04_support")
PrecacheParticleSystem("reference_4_cheap")
PrecacheParticleSystem("snow_04_fog")
PrecacheParticleSystem("reference_4")
PrecacheParticleSystem("snow_04_fog2")
PrecacheParticleSystem("snow_04_small")


PrecacheParticleSystem("smoke_cloud")
PrecacheParticleSystem("smoke_fuss")
PrecacheParticleSystem("smoke_fuss_b")
PrecacheParticleSystem("smoke_grenade_flash")
PrecacheParticleSystem("smoke_grenade_glow")
PrecacheParticleSystem("smoke_grenade_sparks")
PrecacheParticleSystem("smoke_grenade_sparks_b")
PrecacheParticleSystem("smoke_grenade_sparks_c")
PrecacheParticleSystem("smoke_cloud_heavy")
PrecacheParticleSystem("HE_smoke_cloud")
PrecacheParticleSystem("HE_smoke_cloud_heavy")
PrecacheParticleSystem("HE_smoke_fuss")
PrecacheParticleSystem("HE_smoke_fuss_b")
PrecacheParticleSystem("HE_smoke_grenade_flash")
PrecacheParticleSystem("HE_smoke_grenade_glow")
PrecacheParticleSystem("HE_smoke_grenade_smoke")
PrecacheParticleSystem("HE_smoke_grenade_sparks")
PrecacheParticleSystem("HE_smoke_grenade_sparks_b")
PrecacheParticleSystem("HE_smoke_grenade_sparks_c")

PrecacheParticleSystem("dust_motes")
PrecacheParticleSystem("dust_motes_b")
PrecacheParticleSystem("iwo_drip")
PrecacheParticleSystem("iwo_drips_b")
PrecacheParticleSystem("lantern_glow")
PrecacheParticleSystem("iwo_drip_glow")
PrecacheParticleSystem("fire_vehicle_a")
PrecacheParticleSystem("fire_vehicle_b")
PrecacheParticleSystem("fire_vehicle_glow")
PrecacheParticleSystem("fire_vehicle_smoke")
PrecacheParticleSystem("fire_vehicle_smoke_b")
PrecacheParticleSystem("fire_vehicle_c")
PrecacheParticleSystem("iwo_rain")
PrecacheParticleSystem("iwo_rain_b")
PrecacheParticleSystem("crater_smoke")
PrecacheParticleSystem("crater_smoke_b")
PrecacheParticleSystem("crater_embers")
PrecacheParticleSystem("ambient_dust")
PrecacheParticleSystem("cloud_misty")

PrecacheParticleSystem("cloud_cumulus")
PrecacheParticleSystem("cloud_misty_wide")
PrecacheParticleSystem("cloud_misty_huge")
PrecacheParticleSystem("cloud_flats")
PrecacheParticleSystem("cloud_cumulus_night")
PrecacheParticleSystem("fire_vehicles_embers")
PrecacheParticleSystem("env_leaves")
PrecacheParticleSystem("skybox_rockets")
PrecacheParticleSystem("skybox_rockets_smoke")
PrecacheParticleSystem("skybox_rockets_glow")
PrecacheParticleSystem("skybox_rockets_launchflame")
PrecacheParticleSystem("skybox_rockets_launchglow")
PrecacheParticleSystem("skybox_rockets_launchsmoke")
PrecacheParticleSystem("skybox_AA_tracers")
PrecacheParticleSystem("skybox_AA")
PrecacheParticleSystem("skybox_AA_glow")
PrecacheParticleSystem("skybox_AA_muzzle")
PrecacheParticleSystem("skybox_rockets_smoke_night")
PrecacheParticleSystem("skybox_rockets_night")

PrecacheParticleSystem("skybox_rockets_launchsmoke_night")
PrecacheParticleSystem("skybox_rockets_launchflame_night")
PrecacheParticleSystem("skybox_AA_muzzle_b")
PrecacheParticleSystem("skybox_AA_smoke")
PrecacheParticleSystem("skybox_AA_sparks")
PrecacheParticleSystem("skybox_huge_smoke")
PrecacheParticleSystem("skybox_huge_smokeb")
PrecacheParticleSystem("lantern_glow_b")
PrecacheParticleSystem("lantern_glow_C")
PrecacheParticleSystem("skybox_AA_muzzle_c")
PrecacheParticleSystem("skybox_AA_muzzle_d")
PrecacheParticleSystem("crater_smoke_small")
PrecacheParticleSystem("fire_debris")
PrecacheParticleSystem("fire_debris_small")
PrecacheParticleSystem("fire_debris_large")
PrecacheParticleSystem("fire_barrel_flames")
PrecacheParticleSystem("fire_barrel_embers")
PrecacheParticleSystem("fire_barrel")
PrecacheParticleSystem("fire_vehicle")

PrecacheParticleSystem("skybox_fire")
PrecacheParticleSystem("skybox_fire_glow")
PrecacheParticleSystem("ambient_ash")
PrecacheParticleSystem("ambient_leaves")
PrecacheParticleSystem("steam_spray")
PrecacheParticleSystem("steam_spray_b")
PrecacheParticleSystem("steam_spray_c")
PrecacheParticleSystem("steam_drips")
PrecacheParticleSystem("fire_line_X")
PrecacheParticleSystem("fire_line_X_ground")
PrecacheParticleSystem("fire_line_Z_glow")
PrecacheParticleSystem("fire_line_Z")
PrecacheParticleSystem("fire_line_X_glow")
PrecacheParticleSystem("fire_line_Y_glow")
PrecacheParticleSystem("fire_line_Y")
PrecacheParticleSystem("fire_line_Y_ground")
PrecacheParticleSystem("skybox_air_explosions")
PrecacheParticleSystem("skybox_air_explosion")
PrecacheParticleSystem("skybox_air_flashes")
PrecacheParticleSystem("skybox_air_smoke")
PrecacheParticleSystem("skybox_air_explosionsb")
PrecacheParticleSystem("skybox_air_flashesb")
PrecacheParticleSystem("skybox_air_smokeb")

PrecacheParticleSystem("Rocket_Smoke")
PrecacheParticleSystem("Rocket_Smoke_Trail")
PrecacheParticleSystem("artillery_smoke_blue_glow")
PrecacheParticleSystem("artillery_smoke_white")
PrecacheParticleSystem("artillery_smoke_blue")
PrecacheParticleSystem("artillery_smoke_blue_fuss")
PrecacheParticleSystem("artillery_smoke_blue_sparks")
PrecacheParticleSystem("artillery_smoke_red")
PrecacheParticleSystem("artillery_smoke_red_fuss")
PrecacheParticleSystem("artillery_smoke_red_glow")
PrecacheParticleSystem("artillery_smoke_red_sparks")
PrecacheParticleSystem("artillery_smoke_blue_sparks_b")
PrecacheParticleSystem("artillery_smoke_red_sparks_b")
PrecacheParticleSystem("point_flare_red_c")
PrecacheParticleSystem("point_flare_red")
PrecacheParticleSystem("point_flare_red_b")
PrecacheParticleSystem("point_flare_red_d")
PrecacheParticleSystem("point_flare_blue")
PrecacheParticleSystem("point_flare_blue_b")
PrecacheParticleSystem("point_flare_blue_c")
PrecacheParticleSystem("point_flare_blue_d")
PrecacheParticleSystem("point_flare_white")

PrecacheParticleSystem("point_flare_white_b")
PrecacheParticleSystem("point_flare_white_c")
PrecacheParticleSystem("point_flare_white_d")
PrecacheParticleSystem("m79_trail")
PrecacheParticleSystem("m79_trail_b")
PrecacheParticleSystem("mortar_trail")
PrecacheParticleSystem("artillery_smoke_flare")
PrecacheParticleSystem("m79_trail_c")
PrecacheParticleSystem("artillery_smoke_red_fuss")
PrecacheParticleSystem("artillery_smoke_red_glow")
PrecacheParticleSystem("artillery_smoke_red_sparks")
PrecacheParticleSystem("artillery_smoke_blue_sparks_b")
PrecacheParticleSystem("artillery_smoke_red_sparks_b")
PrecacheParticleSystem("point_flare_red_c")
PrecacheParticleSystem("point_flare_red")
PrecacheParticleSystem("point_flare_red_b")
PrecacheParticleSystem("point_flare_red_d")
PrecacheParticleSystem("point_flare_blue")
PrecacheParticleSystem("point_flare_blue_b")
PrecacheParticleSystem("point_flare_blue_c")
PrecacheParticleSystem("point_flare_blue_d")
PrecacheParticleSystem("point_flare_white")

PrecacheParticleSystem("m79_trails")
PrecacheParticleSystem("m79_body_blood")
PrecacheParticleSystem("m79_body_shrapnel_c")
PrecacheParticleSystem("m79_body_gibs")
PrecacheParticleSystem("m79_body_gib_trail")
PrecacheParticleSystem("m79_body_gib_trail_b")
PrecacheParticleSystem("m79_body_gib_trail_fire")
PrecacheParticleSystem("explosion_lensflare")
PrecacheParticleSystem("water_explosion_wake")
PrecacheParticleSystem("water_explosion_wake_b")
PrecacheParticleSystem("water_explosion_wake_c")
PrecacheParticleSystem("water_explosion_splashes")
PrecacheParticleSystem("grenade_flash_c")
PrecacheParticleSystem("party_fireworks")
PrecacheParticleSystem("party_fireworks_trail")
PrecacheParticleSystem("party_fireworks_trailb")
PrecacheParticleSystem("party_fireworks_trailb")
PrecacheParticleSystem("party_fireworks_flashes")
PrecacheParticleSystem("party_fireworksb")
PrecacheParticleSystem("party_fireworks_flash")
PrecacheParticleSystem("party_fireworks_glow")
PrecacheParticleSystem("point_flare_white")


function AddAmmoType(name, text)
	game.AddAmmoType({name = name})
	
	if CLIENT then
		language.Add(name .. "_ammo", text)
	end
end

AddAmmoType("9x19mm", "9x19MM Ammo")
AddAmmoType("9x18mm", "9x18MM Ammo")
AddAmmoType(".45acp", ".45 ACP Ammo")
AddAmmoType(".357magnum", ".357 Magnum Ammo")
AddAmmoType(".454casull", ".454 Casull Ammo")
AddAmmoType(".50ae", ".50 AE Ammo")
AddAmmoType("9x39mm", "9x39MM Ammo")
AddAmmoType("7.62x39mm", "7.62x39MM Ammo")
AddAmmoType("5.56x45mm", "5.56x45MM Ammo")
AddAmmoType("5.45x39mm", "5.45x39MM Ammo")
AddAmmoType("12.7x55mm", "12.7x55MM Ammo")
AddAmmoType("5.7x28mm", "5.7x28MM Ammo")
AddAmmoType(".50bmg", ".50 BMG Ammo")
AddAmmoType("7.62x54mm", "7.62x54MM Ammo")
AddAmmoType("7.62x51mm", "7.62x51MM Ammo")
AddAmmoType(".338lapua", ".338 Lapua Ammo")
AddAmmoType("12gauge", "12 Gauge Ammo")
AddAmmoType("23x75mmr", "23x75MMR Ammo")

AddAmmoType("12gaugeincendiary", "12 Gauge Incendiary Ammo")
AddAmmoType("12gaugeslug", "12 Gauge Slug Ammo")
AddAmmoType("7.62x51mmap", "7.62x51MM AP Ammo")

AddAmmoType("40mmhe", "40MM HE Ammo")
AddAmmoType("40mmsmoke", "40MM Smoke Ammo")
AddAmmoType("M67 Grenades", "M67 Grenades")
AddAmmoType("M18 Grenades", "M18 Grenades")
AddAmmoType("M84 Grenades", "M84 Grenades")